[project]
name = "python-crawl"
version = "0.1.0"
description = "台幣匯率轉換"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
     "requests>=2.0.0",
     "beautifulsoup4>=4.12.2",
     "lxml>=4.9.0",
     "streamlit>=1.32.0",
]
