[project]
name = "python-crawl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
     "crawl4ai>=0.7.8",
     "ipykernel>=7.1.0",
     "playwright>=1.56.0",
]
