[project]
name = "python-crawl"
version = "0.1.0"
description = "台幣匯率轉換"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
     "crawl4ai>=0.7.8",
     "ipykernel>=7.1.0",
     "nest-asyncio>=1.6.0",
     "playwright>=1.56.0",
     "streamlit>=1.32.0",
]
